{
 "title": "prometheus-agent-monitoring$tmpl_var_name_suffix",
 "tags": [
  "last9_managed",
  "$tmpl_var_dashboard_tag"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "datasource",
    "query": "$tmpl_var_prometheus_agent_data_source"
   }
  ]
 },
 "panels": [
  { "title": "remote_write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "prometheus_remote_storage_samples_retried_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(rate(prometheus_remote_storage_samples_retried_total{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prometheus_remote_storage_samples_failed_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(rate(prometheus_remote_storage_samples_failed_total{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prometheus_remote_storage_samples_dropped_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(rate(prometheus_remote_storage_samples_dropped_total{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "processed_percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "((1 - (sum by (instance) (prometheus_remote_storage_samples_pending{url=~\".*\", $tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}) / max by (instance) (rate(prometheus_remote_storage_samples_in_total{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}[1m])*60))) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "bytes_sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(sum by (instance, url) (rate(prometheus_remote_storage_samples_bytes_total{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}[1m])*60 or rate(prometheus_remote_storage_bytes_total{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}[1m])*60) + sum by (instance, url) (rate(prometheus_remote_storage_metadata_bytes_total{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}[1m])*60))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "wal_lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "((max by (instance, url) (max_over_time(prometheus_tsdb_wal_segment_current{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}[1m]))) - (max by (instance, url) (max_over_time(prometheus_wal_watcher_current_segment{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}[1m]))))"
    }
   ]
  },
  {
   "title": "available_shards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(max by (instance, url) (max_over_time(prometheus_remote_storage_shards_max{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}[1m])) - max by (instance, url) (max_over_time(prometheus_remote_storage_shards_desired{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "desired_shards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (instance, url) (prometheus_remote_storage_shards_desired{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "agent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "prometheus_agent_active_series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_agent_active_series{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prometheus_agent_deleted_series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_agent_deleted_series{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prometheus_agent_checkpoint_creation_failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_agent_checkpoint_creations_failed_total{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prometheus_agent_checkpoint_deletion_failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_agent_checkpoint_deletions_failed_total{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prometheus_agent_corruptions_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_agent_corruptions_total{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prometheus_agent_clean_start",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_agent_clean_start{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prometheus_config_last_reload_success_timestamp_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(time() - prometheus_config_last_reload_success_timestamp_seconds{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "targets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "prometheus_target_scrape_pool_targets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "max(prometheus_target_scrape_pool_targets{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}) by (scrape_job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prometheus_target_interval_length_seconds P99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\", quantile=\"0.99\"}",
     "legendFormat": "{{interval}}"
    }
   ]
  },
  {
   "title": "prometheus_target_scrape_pools_failed_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "prometheus_target_scrape_pools_failed_total{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "scrape_series_added",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum without(instance)(sum_over_time(scrape_series_added{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prometheus_config_last_reload_successful",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_successful{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "service_discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "prometheus_sd_failed_configs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "prometheus_sd_failed_configs{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prometheus_sd_discovered_targets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "expr": "prometheus_sd_discovered_targets{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}",
     "legendFormat": "{{name}}-{{config}}"
    }
   ]
  },
  {
   "title": "total_prometheus_sd_discovered_targets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "sum(prometheus_sd_discovered_targets{$tmpl_var_prometheus_agent_metrics_label_key=~\"$tmpl_var_prometheus_agent_metrics_label_value_regex\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "resources_used", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "container_memory_usage_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (container_memory_usage_bytes{pod=~\"$tmpl_var_prometheus_agent_pod_regex\", container!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (rate(container_cpu_usage_seconds_total{pod=~\"$tmpl_var_prometheus_agent_pod_regex\", container!=\"\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}