#!/bin/bash

set -eou pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

set -x

# shellcheck disable=2048
# shellcheck disable=2086
"$SCRIPT_DIR/enable-alerts" --type vmagent --edit-config $*
